services:
  hbbs:
    image: "rustdesk/rustdesk-server:latest"
    container_name: "hbbs"
    depends_on:
      hbbr:
    restart: "unless-stopped"
    command: ["hbbs"]
    ports:
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21118:21118"
    volumes:
      - "./data:/root"

  hbbr:
    image: "rustdesk/rustdesk-server:latest"
    container_name: "hbbr"
    restart: "unless-stopped"
    command: ["hbbr"]
    ports:
      - "21117:21117"
      - "21119:21119"
    volumes:
      - "./data:/root"
