services:
  blog_web:
    image: "nginx:alpine"
    container_name: "blog_web"
    restart: "unless-stopped"
    labels:
      traefik.enable: true
      traefik.http.services.blog_web.loadbalancer.server.port: "80"
      traefik.http.routers.blog.rule: "Host(`blog.${BASEURL:?error}`)"
      traefik.http.routers.blog.entrypoints: "websecure"
      traefik.http.routers.blog.tls.certresolver: "cloudflare"
      traefik.http.routers.blog.service: "blog_web"
    networks:
      frontend:
    volumes:
      - "./data/myblog/docs:/usr/share/nginx/html:ro"
    deploy:
      resources:
        limits:
          memory: "1G"

  blog_updater:
    image: "jamesread/olivetin"
    container_name: "blog_updater"
    restart: "unless-stopped"
    user: "root"
    labels:
      traefik.enable: true
      traefik.http.services.blog_updater.loadbalancer.server.port: "1337"
      traefik.http.routers.blog_updater.rule: "Host(`blog-updater.${BASEURL:?error}`) && PathPrefix(`/api/`)"
      traefik.http.routers.blog_updater.tls.certresolver: "cloudflare"
      traefik.http.routers.blog_updater.entrypoints: "websecure"
      traefik.http.routers.blog_updater.service: "blog_updater"
    networks:
      frontend:
    volumes:
      - "./config/olivetin.yaml/:/config/config.yaml:ro"
      - "./data:/data"
    deploy:
      resources:
        limits:
          memory: "1G"

networks:
  frontend:
    external: true
